'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Clock3, FileText, Pencil, Plus, Trash2, Trophy, X } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { useToast } from '@/hooks/use-toast';
import { getBDDateString, getBDTimeString } from '@/lib/date-utils';

type ExamType = 'CLASS_TEST' | 'MID' | 'FINAL';
type Exam = { id: string; title: string; subject: string | null; examType: ExamType; examDate: string; examTime: string; durationMinutes: number | null; topics: string; approximateMarks: number | null; questionMaterial: string | null; notes: string | null };
type ExamForm = { title: string; subject: string; examType: ExamType; examDate: string; examTime: string; durationMinutes: string; topics: string; approximateMarks: string; questionMaterial: string; notes: string };
const emptyForm: ExamForm = { title: '', subject: '', examType: 'CLASS_TEST', examDate: '', examTime: '', durationMinutes: '', topics: '', approximateMarks: '', questionMaterial: '', notes: '' };
const typeLabel: Record<ExamType, string> = { CLASS_TEST: 'Class Test', MID: 'Mid', FINAL: 'Final' };
const parseTopics = (value: string) => { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed : []; } catch { return []; } };

export default function ExamsPage() {
  const [exams, setExams] = useState<Exam[]>([]);
  const [form, setForm] = useState<ExamForm>(emptyForm);
  const [statusFilter, setStatusFilter] = useState<'INCOMING' | 'ALL' | 'TAKEN'>('INCOMING');
  const [typeFilter, setTypeFilter] = useState<'ALL' | ExamType>('ALL');
  const [editing, setEditing] = useState<Exam | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const { toast } = useToast();

  const loadExams = async () => { const response = await fetch('/api/exams', { cache: 'no-store' }); if (response.ok) setExams(await response.json()); };
  useEffect(() => { void loadExams(); }, []);
  const isTaken = (exam: Exam) => exam.examDate.slice(0, 10) < getBDDateString() || (exam.examDate.slice(0, 10) === getBDDateString() && exam.examTime <= getBDTimeString());
  const statusBadge = (exam: Exam) => <Badge className={isTaken(exam) ? 'bg-slate-200 text-slate-700 hover:bg-slate-200' : 'bg-emerald-100 text-emerald-700 hover:bg-emerald-100'}>{isTaken(exam) ? 'Taken' : 'Coming'}</Badge>;
  const visibleExams = useMemo(() => exams.filter((exam) => (statusFilter === 'ALL' || (statusFilter === 'TAKEN' ? isTaken(exam) : !isTaken(exam))) && (typeFilter === 'ALL' || exam.examType === typeFilter)), [exams, statusFilter, typeFilter]);
  const updateForm = (key: keyof ExamForm, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const openCreate = () => { setEditing(null); setForm(emptyForm); setShowForm(true); };
  const openEdit = (exam: Exam) => { setEditing(exam); setForm({ title: exam.title, subject: exam.subject || '', examType: exam.examType, examDate: exam.examDate.slice(0, 10), examTime: exam.examTime, durationMinutes: exam.durationMinutes?.toString() || '', topics: parseTopics(exam.topics).join(', '), approximateMarks: exam.approximateMarks?.toString() || '', questionMaterial: exam.questionMaterial || '', notes: exam.notes || '' }); setShowForm(true); };
  const saveExam = async () => { setSaving(true); const response = await fetch('/api/exams', { method: editing ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: editing?.id, ...form, topics: form.topics.split(',').map((topic) => topic.trim()).filter(Boolean) }) }); setSaving(false); if (!response.ok) { const error = await response.json(); toast({ title: 'Could not save exam', description: error.error, variant: 'destructive' }); return; } setShowForm(false); setEditing(null); setForm(emptyForm); await loadExams(); toast({ title: editing ? 'Exam updated' : 'Exam added', description: 'Your exam plan is up to date.' }); };
  const deleteExam = async (id: string) => { if (!confirm('Delete this exam?')) return; const response = await fetch(`/api/exams?id=${id}`, { method: 'DELETE' }); if (response.ok) { setExams((current) => current.filter((exam) => exam.id !== id)); toast({ title: 'Exam deleted' }); } };
  const formatDate = (date: string) => new Intl.DateTimeFormat('en-US', { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric', timeZone: 'UTC' }).format(new Date(date));

  return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-cyan-50/40 to-white px-4 py-8 text-slate-900 sm:px-6"><div className="mx-auto max-w-6xl"><section className="mb-7 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><div className="mb-3 flex items-center gap-3"><div className="rounded-2xl bg-slate-950 p-3"><Trophy className="h-7 w-7 text-cyan-300" /></div><div><h1 className="text-3xl font-bold tracking-tight md:text-4xl">Exams</h1><p className="mt-1 text-sm text-slate-500">Plan every exam, topic, question and target score in one place.</p></div></div></div><Button onClick={openCreate} className="h-11 rounded-xl bg-slate-950 px-5 text-white hover:bg-slate-800"><Plus className="mr-2 h-4 w-4" />Add exam</Button></div><div className="mt-7 flex flex-wrap gap-2">{(['INCOMING', 'ALL', 'TAKEN'] as const).map((value) => <Button key={value} size="sm" variant={statusFilter === value ? 'default' : 'outline'} onClick={() => setStatusFilter(value)}>{value === 'INCOMING' ? 'Incoming exams' : value === 'ALL' ? 'All exams' : 'Taken exams'}</Button>)}</div><div className="mt-3 flex flex-wrap gap-2">{(['ALL', 'CLASS_TEST', 'MID', 'FINAL'] as const).map((value) => <Button key={value} size="sm" variant={typeFilter === value ? 'secondary' : 'ghost'} onClick={() => setTypeFilter(value)}>{value === 'ALL' ? 'All types' : typeLabel[value]}</Button>)}</div></section>
  {showForm && <Card className="mb-7 border-cyan-200 shadow-sm"><CardHeader className="flex-row items-center justify-between"><CardTitle>{editing ? 'Edit exam' : 'Add exam'}</CardTitle><Button variant="ghost" size="icon" onClick={() => setShowForm(false)}><X className="h-4 w-4" /></Button></CardHeader><CardContent className="grid gap-4 md:grid-cols-2"><div><Label>Exam title *</Label><Input value={form.title} onChange={(e) => updateForm('title', e.target.value)} placeholder="Digital Communication Final" /></div><div><Label>Subject</Label><Input value={form.subject} onChange={(e) => updateForm('subject', e.target.value)} placeholder="Subject name" /></div><div><Label>Exam type *</Label><select value={form.examType} onChange={(e) => updateForm('examType', e.target.value)} className="flex h-10 w-full rounded-md border bg-background px-3 text-sm"><option value="CLASS_TEST">Class Test</option><option value="MID">Mid</option><option value="FINAL">Final</option></select></div><div><Label>Exam date *</Label><Input type="date" value={form.examDate} onChange={(e) => updateForm('examDate', e.target.value)} /></div><div><Label>Exam time *</Label><Input type="time" value={form.examTime} onChange={(e) => updateForm('examTime', e.target.value)} /></div><div><Label>Duration (minutes)</Label><Input type="number" min="1" value={form.durationMinutes} onChange={(e) => updateForm('durationMinutes', e.target.value)} placeholder="120" /></div><div><Label>Approximate marks</Label><Input type="number" min="0" value={form.approximateMarks} onChange={(e) => updateForm('approximateMarks', e.target.value)} placeholder="80" /></div><div><Label>Topics</Label><Input value={form.topics} onChange={(e) => updateForm('topics', e.target.value)} placeholder="Signals, Modulation, Noise" /><p className="mt-1 text-xs text-slate-500">Separate topics with commas.</p></div><div className="md:col-span-2"><Label>Question / material link</Label><Input value={form.questionMaterial} onChange={(e) => updateForm('questionMaterial', e.target.value)} placeholder="https://... or file link" /></div><div className="md:col-span-2"><Label>Notes</Label><Textarea value={form.notes} onChange={(e) => updateForm('notes', e.target.value)} placeholder="Preparation notes, room, or instructions" /></div><div className="flex justify-end gap-2 md:col-span-2"><Button variant="outline" onClick={() => setShowForm(false)}>Cancel</Button><Button onClick={saveExam} disabled={saving}>{saving ? 'Saving...' : editing ? 'Save changes' : 'Add exam'}</Button></div></CardContent></Card>}
  <div className="space-y-4">{visibleExams.length === 0 ? <Card><CardContent className="py-16 text-center"><CalendarDays className="mx-auto mb-4 h-12 w-12 text-slate-300" /><h2 className="text-lg font-semibold">No exams scheduled</h2><p className="mt-1 text-sm text-slate-500">Add your next exam to build a clear preparation timeline.</p></CardContent></Card> : visibleExams.map((exam, index) => <Card key={exam.id} className="overflow-hidden border-slate-200 shadow-sm"><CardContent className="p-5 md:p-6"><div className="flex flex-col gap-5 md:flex-row md:items-start"><div className="min-w-[150px] rounded-2xl bg-slate-950 p-4 text-white"><div className="text-xs font-semibold uppercase tracking-wide text-cyan-300">Exam {index + 1}</div><div className="mt-2 text-lg font-bold">{formatDate(exam.examDate)}</div><div className="mt-1 flex items-center gap-1 text-sm text-slate-300"><Clock3 className="h-3.5 w-3.5" />{exam.examTime}</div></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold">{exam.title}</h2><Badge variant="outline">{typeLabel[exam.examType]}</Badge>{statusBadge(exam)}{exam.subject && <Badge variant="secondary">{exam.subject}</Badge>}</div><div className="mt-3 flex flex-wrap gap-2">{parseTopics(exam.topics).map((topic: string) => <Badge key={topic} className="bg-cyan-50 text-cyan-700 hover:bg-cyan-50">{topic}</Badge>)}</div><div className="mt-4 grid gap-2 text-sm text-slate-600 sm:grid-cols-3"><span>{exam.durationMinutes ? `${exam.durationMinutes} min` : 'Duration not set'}</span><span>{exam.approximateMarks !== null ? `Target: ${exam.approximateMarks} marks` : 'Target not set'}</span>{exam.questionMaterial ? <a href={exam.questionMaterial} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-medium text-cyan-700 hover:underline"><FileText className="h-4 w-4" />Question material</a> : <span>No material linked</span>}</div>{exam.notes && <p className="mt-3 whitespace-pre-wrap text-sm text-slate-500">{exam.notes}</p>}</div><div className="flex shrink-0 gap-1"><Button variant="ghost" size="icon" onClick={() => openEdit(exam)} title="Edit exam"><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => deleteExam(exam.id)} title="Delete exam"><Trash2 className="h-4 w-4 text-red-500" /></Button></div></div></CardContent></Card>)}</div></div></main>;
}